version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: config/docker/backend.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - TENNIS_ENVIRONMENT=production
      - DYNAMODB_ENDPOINT=https://dynamodb.us-east-1.amazonaws.com
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TENNIS_HEADLESS=true
    depends_on:
      - dynamodb
    networks:
      - tennis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../..
      dockerfile: config/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8001
    depends_on:
      - backend
    networks:
      - tennis-network
    restart: unless-stopped

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - tennis-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - tennis-network
    restart: unless-stopped

volumes:
  dynamodb-data:

networks:
  tennis-network:
    driver: bridge